version: "3.8"

volumes:
  node-modules:
  
services:
  frontend:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
