version: "3.8"

volumes:
  node-modules:
  
services:
  frontend:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/app
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"
